TRACE_ID_KEY = "trace_id"
SPAN_ID_KEY = "span_id"
REQUEST_ID_KEY = "request_id"
EXTRA_LOG_FIELDS_KEY = "extra"
FILE_KEY = "file"
ERROR_KEY = "error"
TRACEBACK_KEY = "traceback"

HTTP_METHOD_KEY = "http.request.method"
HTTP_STATUS_KEY = "http.response.status_code"
HTTP_ROUTE_KEY = "http.route"
HTTP_REQUEST_DURATION_KEY = "http.server.request.duration"

REQUEST_DURATION_METRIC = "http.server.request.duration"
ACTIVE_REQUESTS_METRIC = "http.server.active_requests"
REQUEST_BODY_SIZE_METRIC = "http.server.request.body.size"
RESPONSE_BODY_SIZE_METRIC = "http.server.response.body.size"
OK_REQUEST_TOTAL_METRIC = "http.server.ok.request.total"
ERROR_REQUEST_TOTAL_METRIC = "http.server.error.request.total"

TRACE_ID_HEADER = "X-Trace-ID"
SPAN_ID_HEADER = "X-Span-ID"
